- name: Deploy docker-manage-windows
  hosts: all
  remote_user: root

  vars:
    DNS: '8.8.8.8'
    DNS_SEARCH: 'test.loc'
    DOMAIN: 'test.loc'
    KDC: 'kdc'
    CRON: '0 0 * * *'

  tasks:
      - set_fact:
          container_home: /var/lib/pylonlabs/manage-windows

      - name: "DEPLOY | Creating Playbook Folder"
        file:
            path: "{{ container_home  }}"
            state: directory

      - name: "DEPLOY | Uploading Playbook"
        synchronize:
            src: ./playbook/
            dest: "{{ container_home }}/playbook"
            rsync_opts: --exclude=.git --exclude=build.* --exclude=.vagrant --exclude=Vagrantfile --exclude=tests 
            copy_links: yes

      - name: "DEPLOY | Orchestrating Container"
        docker_service:
          state: present
          project_name: "manage-windows"
          definition:
            version: '2'
            services:
              manage:
                image: alinmear/docker-manage-windows:latest
                volumes:
                  - "{{ container_home }}/playbook:/opt/manage-windows"
                dns:
                  - "{{ DNS }}"
                dns_search:
                  - "{{ DNS_SEARCH }}"
                environment:
                  - "MANAGEWINDOWS_DOMAIN={{ DOMAIN }}"
                  - "MANAGEWINDOWS_KDC={{ KDC }}"
                  - "MANAGEWINDOWS_CRON={{ CRON }}"
