version: '2'

services:
  manage:
    image: alinmear/docker-manage-windows
    container_name: manage-windows
    volumes:
      - ./playbook:/opt/manage-windows
    dns:
      - 8.8.8.8
    dns_search:
      - example.com
    environment:
      - MANAGEWINDOWS_DOMAIN=example.com
      - MANAGEWINDOWS_CRON='0 0 * * *'
      - MANAGEWINDOWS_KDC='kdc'
